# Generated by Django 6.0 on 2025-12-11 06:06

import django.db.models.deletion
import echs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0009_alter_customuser_options_customuser_ward_other_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EchsPatientMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.PositiveIntegerField(unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('date_of_discharge', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CapturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to=echs.models.upload_to)),
                ('folder_path', models.CharField(blank=True, max_length=255, null=True)),
                ('image_size', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('custom_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echs_capturedimage_tags', to='members.customtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echs_captured_images', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_captured_images', to='echs.echspatientmaster')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to=echs.models.upload_to)),
                ('folder_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('custom_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echs_uploadedfile_tags', to='members.customtag')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='echs.echspatientmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echs_uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to=echs.models.upload_to)),
                ('folder_path', models.CharField(blank=True, max_length=255, null=True)),
                ('image_size', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('custom_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echs_uploadedimage_tags', to='members.customtag')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='echs.echspatientmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echs_uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
