# Generated by Django 6.0 on 2025-12-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='echspatientmaster',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='echspatientmaster',
            name='date_of_admission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='echspatientmaster',
            name='date_of_discharge',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
