# Generated by Django 6.0 on 2025-12-15 07:08

import django.db.models.deletion
import echs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echs', '0003_echspatientmaster_created_by_and_more'),
        ('members', '0009_alter_customuser_options_customuser_ward_other_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherUploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to=echs.models.upload_to)),
                ('folder_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('custom_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_files', to='members.customtag')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converted_files', to='echs.echspatientmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converted_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
