# Generated by Django 6.0 on 2025-12-18 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echs', '0008_otheruploadedfile_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otheruploadedfile',
            name='captured_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_file', to='echs.capturedimage'),
        ),
    ]
