# Generated by Django 6.0 on 2025-12-18 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('echs', '0009_otheruploadedfile_captured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otheruploadedfile',
            name='captured_image',
        ),
        migrations.AddField(
            model_name='otheruploadedfile',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='otheruploadedfile',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
