# Generated by Django 5.2 on 2025-04-28 07:54

import capture.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.PositiveIntegerField()),
                ('image_path', models.ImageField(upload_to=capture.models.upload_to)),
                ('folder_path', models.CharField(blank=True, max_length=255, null=True)),
                ('image_size', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedCapturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.PositiveIntegerField()),
                ('uhid', models.PositiveIntegerField()),
                ('image_path', models.CharField(max_length=255)),
                ('folder_path', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('image_size', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedUploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.PositiveIntegerField()),
                ('uhid', models.PositiveIntegerField()),
                ('file_path', models.CharField(max_length=255)),
                ('folder_path', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.PositiveIntegerField()),
                ('file_path', models.FileField(upload_to=capture.models.upload_to)),
                ('folder_path', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
