# Generated by Django 5.2 on 2025-05-02 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0002_initial'),
        ('members', '0004_alter_customtag_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='custom_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.customtag'),
        ),
    ]
