# Generated by Django 5.2 on 2025-05-17 10:12

import capture.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0004_uploadedimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Describe the issue', verbose_name='Issue Description')),
                ('attachment', models.FileField(blank=True, help_text='Attach an image or PDF (optional, max 10MB)', null=True, upload_to=capture.models.issue_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('issue_id', models.CharField(default=capture.models.generate_unique_issue_id, editable=False, max_length=6, unique=True)),
                ('current_status', models.CharField(choices=[('open', 'Action Pending'), ('accepted', 'Under Process'), ('rejected', 'Not Feasible'), ('completed', 'Completed')], default='open', max_length=20)),
                ('current_status_marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_remark', models.TextField(blank=True, help_text='Optional remarks from admin', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
