# Generated by Django 5.2 on 2025-05-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtag',
            name='type',
            field=models.CharField(choices=[('Universal', 'Universal'), ('Geo-Pic', 'Geo-Pic'), ('File Only', 'File Only')], default='Universal', max_length=20),
        ),
    ]
