# Generated by Django 5.2 on 2025-05-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_customtag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtag',
            name='value',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
