# Generated by Django 5.2 on 2025-05-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_customtag_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtag',
            name='value',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
