# Generated by Django 5.2 on 2025-05-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_department_created_at_department_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department_other',
            field=models.CharField(blank=True, help_text='If you select ‘Others’ above, specify here.', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation_other',
            field=models.CharField(blank=True, help_text='If you select ‘Others’ above, specify here.', max_length=255),
        ),
    ]
