# Generated by Django 5.2 on 2025-05-17 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_customuser_department_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number may start with '+', and contain only digits, spaces, and hyphens.", regex='^\\+?[\\d\\-\\s]+$')]),
        ),
    ]
